-- MySQL Script generated by MySQL Workbench
-- Wed Mar  8 12:00:27 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id_users` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(256) NULL,
  `password` VARCHAR(256) NULL,
  `remember` VARCHAR(256) NULL,
  PRIMARY KEY (`id_users`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`technicalnotes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`technicalnotes` (
  `id_technicalnote` INT NOT NULL,
  `idx_user` INT NOT NULL,
  `name` VARCHAR(256) NULL,
  `lastedit` DATETIME NULL,
  `pincode` INT NULL,
  `linkhash` VARCHAR(256) NULL,
  PRIMARY KEY (`id_technicalnote`),
  INDEX `fk_technicalnotes_users_idx` (`idx_user` ASC),
  CONSTRAINT `fk_technicalnotes_users`
    FOREIGN KEY (`idx_user`)
    REFERENCES `mydb`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`informations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`informations` (
  `id_information` INT NOT NULL AUTO_INCREMENT,
  `idx_technicalnote` INT NOT NULL,
  `band` VARCHAR(256) NULL,
  `date` DATETIME NULL,
  `stageplan` VARCHAR(256) NULL,
  PRIMARY KEY (`id_information`),
  INDEX `fk_informations_technicalnotes1_idx` (`idx_technicalnote` ASC),
  CONSTRAINT `fk_informations_technicalnotes1`
    FOREIGN KEY (`idx_technicalnote`)
    REFERENCES `mydb`.`technicalnotes` (`id_technicalnote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`patchlists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`patchlists` (
  `id_patchlist` INT NOT NULL,
  `idx_technicalnote` INT NOT NULL,
  `input` VARCHAR(128) NULL,
  `instrument` VARCHAR(256) NULL,
  `microphone` VARCHAR(256) NULL,
  `fx` VARCHAR(256) NULL,
  `monitormix` VARCHAR(256) NULL,
  PRIMARY KEY (`id_patchlist`),
  INDEX `fk_patchlists_technicalnotes1_idx` (`idx_technicalnote` ASC),
  CONSTRAINT `fk_patchlists_technicalnotes1`
    FOREIGN KEY (`idx_technicalnote`)
    REFERENCES `mydb`.`technicalnotes` (`id_technicalnote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`musicians`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`musicians` (
  `id_musician` INT NOT NULL,
  `Idx_technicalnote` INT NOT NULL,
  `name` VARCHAR(256) NULL,
  `instrument` VARCHAR(256) NULL,
  PRIMARY KEY (`id_musician`),
  INDEX `fk_musicians_technicalnotes1_idx` (`Idx_technicalnote` ASC),
  CONSTRAINT `fk_musicians_technicalnotes1`
    FOREIGN KEY (`Idx_technicalnote`)
    REFERENCES `mydb`.`technicalnotes` (`id_technicalnote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comments` (
  `id_comments` INT NOT NULL AUTO_INCREMENT,
  `idx_technicalnote` INT NOT NULL,
  `head` VARCHAR(256) NULL,
  `commentar` LONGTEXT NULL,
  `title` VARCHAR(256) NULL,
  PRIMARY KEY (`id_comments`),
  INDEX `fk_commentars_technicalnotes1_idx` (`idx_technicalnote` ASC),
  CONSTRAINT `fk_commentars_technicalnotes1`
    FOREIGN KEY (`idx_technicalnote`)
    REFERENCES `mydb`.`technicalnotes` (`id_technicalnote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contacts` (
  `id_contact` INT NOT NULL AUTO_INCREMENT,
  `idx_technicalnote` INT NOT NULL,
  `name` VARCHAR(256) NULL,
  `email` VARCHAR(256) NULL,
  `phone` VARCHAR(256) NULL,
  `website` VARCHAR(256) NULL,
  PRIMARY KEY (`id_contact`),
  INDEX `fk_contacts_technicalnotes1_idx` (`idx_technicalnote` ASC),
  CONSTRAINT `fk_contacts_technicalnotes1`
    FOREIGN KEY (`idx_technicalnote`)
    REFERENCES `mydb`.`technicalnotes` (`id_technicalnote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
