-- MySQL Script generated by MySQL Workbench
-- Fri Mar 10 10:37:29 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema technote
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema technote
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `technote` DEFAULT CHARACTER SET utf8 ;
USE `technote` ;

-- -----------------------------------------------------
-- Table `technote`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technote`.`users` (
  `id_users` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(256) NULL,
  `password` VARCHAR(256) NULL,
  `remember` VARCHAR(256) NULL,
  PRIMARY KEY (`id_users`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `technote`.`technicalnotes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technote`.`technicalnotes` (
  `id_technicalnote` INT NOT NULL AUTO_INCREMENT,
  `idx_user` INT NOT NULL,
  `name` VARCHAR(256) NULL,
  `lastedit` DATETIME NULL,
  `pincode` INT NULL,
  `linkhash` VARCHAR(256) NULL,
  PRIMARY KEY (`id_technicalnote`),
  INDEX `fk_technicalnotes_users_idx` (`idx_user` ASC),
  CONSTRAINT `fk_technicalnotes_users`
    FOREIGN KEY (`idx_user`)
    REFERENCES `technote`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `technote`.`informations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technote`.`informations` (
  `id_information` INT NOT NULL AUTO_INCREMENT,
  `idx_technicalnote` INT NOT NULL,
  `band` VARCHAR(256) NULL,
  `date` DATETIME NULL,
  `stageplan` VARCHAR(256) NULL,
  PRIMARY KEY (`id_information`),
  INDEX `fk_informations_technicalnotes1_idx` (`idx_technicalnote` ASC),
  CONSTRAINT `fk_informations_technicalnotes1`
    FOREIGN KEY (`idx_technicalnote`)
    REFERENCES `technote`.`technicalnotes` (`id_technicalnote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `technote`.`patchlists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technote`.`patchlists` (
  `id_patchlist` INT NOT NULL AUTO_INCREMENT,
  `idx_technicalnote` INT NOT NULL,
  `input` VARCHAR(128) NULL,
  `instrument` VARCHAR(256) NULL,
  `microphone` VARCHAR(256) NULL,
  `fx` VARCHAR(256) NULL,
  `monitormix` VARCHAR(256) NULL,
  PRIMARY KEY (`id_patchlist`),
  INDEX `fk_patchlists_technicalnotes1_idx` (`idx_technicalnote` ASC),
  CONSTRAINT `fk_patchlists_technicalnotes1`
    FOREIGN KEY (`idx_technicalnote`)
    REFERENCES `technote`.`technicalnotes` (`id_technicalnote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `technote`.`musicians`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technote`.`musicians` (
  `id_musician` INT NOT NULL AUTO_INCREMENT,
  `Idx_technicalnote` INT NOT NULL,
  `name` VARCHAR(256) NULL,
  `instrument` VARCHAR(256) NULL,
  PRIMARY KEY (`id_musician`),
  INDEX `fk_musicians_technicalnotes1_idx` (`Idx_technicalnote` ASC),
  CONSTRAINT `fk_musicians_technicalnotes1`
    FOREIGN KEY (`Idx_technicalnote`)
    REFERENCES `technote`.`technicalnotes` (`id_technicalnote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `technote`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technote`.`comments` (
  `id_comments` INT NOT NULL AUTO_INCREMENT,
  `idx_technicalnote` INT NOT NULL,
  `head` VARCHAR(256) NULL,
  `commentar` LONGTEXT NULL,
  `title` VARCHAR(256) NULL,
  PRIMARY KEY (`id_comments`),
  INDEX `fk_commentars_technicalnotes1_idx` (`idx_technicalnote` ASC),
  CONSTRAINT `fk_commentars_technicalnotes1`
    FOREIGN KEY (`idx_technicalnote`)
    REFERENCES `technote`.`technicalnotes` (`id_technicalnote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `technote`.`contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technote`.`contacts` (
  `id_contact` INT NOT NULL AUTO_INCREMENT,
  `idx_technicalnote` INT NOT NULL,
  `name` VARCHAR(256) NULL,
  `email` VARCHAR(256) NULL,
  `phone` VARCHAR(256) NULL,
  `website` VARCHAR(256) NULL,
  `function` VARCHAR(256) NULL,
  PRIMARY KEY (`id_contact`),
  INDEX `fk_contacts_technicalnotes1_idx` (`idx_technicalnote` ASC),
  CONSTRAINT `fk_contacts_technicalnotes1`
    FOREIGN KEY (`idx_technicalnote`)
    REFERENCES `technote`.`technicalnotes` (`id_technicalnote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
